"""
Adjudication actuator — drafts the denial/approval letter and the FHIR
ClaimResponse payload from the agent's decision + cited evidence.

BUILT LIVE (18 Sept): deliberately template-based, not LLM-freeform. Every
sentence traces to a field already produced by a tool call (trajectory
result, matched policy, interaction result) so the letter can't say
anything the audit trail doesn't already support — that's the whole
"legally defensible" claim in the spec, and an LLM-generated letter body
would undercut it.
"""
from datetime import datetime, timezone


def build_fhir_claim_response(claim: dict, status: str, adjudication_id: str) -> dict:
    """Minimal FHIR ClaimResponse resource for the decision."""
    return {
        "resourceType": "ClaimResponse",
        "id": adjudication_id,
        "status": "active",
        "outcome": "complete",
        "disposition": status,
        "patient": {"reference": f"Patient/{claim.get('patient_id')}"},
        "request": {"reference": f"Claim/{claim.get('claim_id')}"},
        "created": datetime.now(timezone.utc).isoformat(),
    }


def generate_letter(
    *,
    claim: dict,
    status: str,
    trajectory_result: dict | None,
    policy_result: dict | None,
    interaction_result: dict | None,
    matched_policy: dict | None,
) -> str:
    lines = []
    lines.append(f"RE: Claim {claim.get('claim_id')} — Patient {claim.get('patient_id')}")
    lines.append(f"CPT {claim.get('cpt_code')} / ICD-10 {claim.get('icd10_code')}")
    lines.append("")
    lines.append(f"DECISION: {status}")
    lines.append("")

    if matched_policy:
        lines.append(
            f"Coverage policy applied: {matched_policy.get('policy_id')} "
            f"— \"{matched_policy.get('title')}\" ({matched_policy.get('payer_name')})."
        )
        if matched_policy.get("step_therapy_required"):
            lines.append(
                "This policy requires documented conservative/step therapy "
                "prior to approval."
            )
        lines.append("")

    if trajectory_result:
        duration = trajectory_result.get("therapy_duration_days", 0)
        required = trajectory_result.get("required_duration_days", 0)
        met = trajectory_result.get("step_therapy_met")
        lines.append(
            f"Clinical trajectory review: {trajectory_result.get('total_conservative_encounters', 0)} "
            f"conservative-therapy encounter(s) found spanning {duration} day(s) "
            f"(policy requires {required} day(s))."
        )
        lines.append(
            "Step-therapy requirement: "
            + ("MET." if met else "NOT MET — insufficient documented duration.")
        )
        lines.append("")

    if interaction_result and interaction_result.get("hits", {}).get("hits"):
        for hit in interaction_result["hits"]["hits"]:
            src = hit["_source"]
            lines.append(
                f"DRUG INTERACTION ALERT ({src.get('severity')}): "
                f"{src.get('drug_a_name')} + {src.get('drug_b_name')} — "
                f"{src.get('mechanism')} (see {src.get('fda_citation')})."
            )
        lines.append("")

    lines.append(
        "This determination was generated by MediAudit-X and is based solely "
        "on the cited evidence in the attached audit record. Every citation "
        "traces to a specific source document and offset; see the audit "
        "ledger entry for this adjudication for the tamper-evident record."
    )
    lines.append("")
    lines.append("This is not a final clinical or coverage determination until "
                  "countersigned by a human reviewer.")
    return "\n".join(lines)
